name: Validate

on:
  workflow_call:

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/_lint.yaml
    secrets: inherit

  security:
    name: security
    uses: ./.github/workflows/_security.yaml
    secrets: inherit

  coverage:
    name: coverage
    uses: ./.github/workflows/_coverage.yaml
    secrets: inherit
